User.find(1).interests << Interest.find(5)
User.find(1).interests << Interest.find(1)
User.find(1).interests << Interest.find(4)
User.find(1).skills << Skill.find(8)
User.find(1).skills << Skill.find(1)

User.find(2).interests << Interest.find(2)
User.find(2).interests << Interest.find(9)
User.find(2).interests << Interest.find(1)
User.find(2).interests << Interest.find(4)
User.find(2).skills << Skill.find(4)
User.find(2).skills << Skill.find(10)

User.find(3).interests << Interest.find(5)
User.find(3).interests << Interest.find(11)
User.find(3).skills << Skill.find(6)
User.find(3).skills << Skill.find(1)
User.find(3).skills << Skill.find(5)

User.find(4).interests << Interest.find(6)
User.find(4).interests << Interest.find(3)
User.find(4).skills << Skill.find(11)
User.find(4).skills << Skill.find(2)
User.find(4).skills << Skill.find(5)

User.find(5).interests << Interest.find(7)
User.find(5).interests << Interest.find(8)
User.find(5).skills << Skill.find(9)
User.find(5).skills << Skill.find(7)
User.find(5).skills << Skill.find(4)

User.find(6).interests << Interest.find(1)
User.find(6).interests << Interest.find(2)
User.find(6).skills << Skill.find(9)
User.find(6).skills << Skill.find(2)
User.find(6).skills << Skill.find(4)

User.find(7).interests << Interest.find(10)
User.find(7).interests << Interest.find(3)
User.find(7).skills << Skill.find(8)
User.find(7).skills << Skill.find(2)
User.find(7).skills << Skill.find(4)

User.find(8).interests << Interest.find(4)
User.find(8).interests << Interest.find(8)
User.find(8).interests << Interest.find(9)
User.find(8).skills << Skill.find(10)
User.find(8).skills << Skill.find(1)
User.find(8).skills << Skill.find(4)